language: ruby
sudo: false
rvm:
  - 2.2
install:
  - gem install jekyll
  - gem install jekyll-paginate
  - gem install html-proofer
script:
  - jekyll build
  #- htmlproof ./_site --only-4xx --check-html
env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer
