language: ruby
sudo: false
rvm:
  - 2.2.5
before_install:
  - gem update --system
  - gem --version
before_script:
  - bundle clean --force
install:
  - gem install jekyll
  - gem install jekyll-paginate
  - gem install html-proofer
  - gem install jemoji
  - gem install listen --version '3.0'
  - gem install addressable --version '2.4.0'
  - gem install github-pages
script:
  - jekyll build
  #- htmlproof ./_site --only-4xx --check-html
env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer
notifications:
  email:
    on_success: never
