# Setup
title: klashxx
tagline: unix linux nonsense
description: "awk go python sysadmin and much more"
image: /images/awk_flow.png
url: https://klashxx.github.io
baseurl: ""
paginate: 5
paginate_path: "page:num"
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  syntax_highlighter: rouge
future: true

gems:
  - jekyll-paginate
  - jemoji
  - jekyll-sitemap
  - jekyll-seo-tag

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _sass
  style:            :compressed

# About/contact
author:
  name:              Juan Diego Godoy Robles
  url:               https://github.com/klashxx
  email:             klashxx@gmail.com

twitter_username: klashxx
github_username:  klashxx

# Custom vars
version:             2.0.0
github:
  repo:              github.com/klashxx/klashxx.github.io

pages_list:
  Archive: '/archive'
  About: '/about'
  Talks: '/talks'
  Feed: '/atom.xml'
